//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeacherApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public int GenderId { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string ResidentialAddress { get; set; }
        public int GroupId { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public System.DateTime LastLogin { get; set; }
        public byte[] MainImage { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Group Group { get; set; }
    }
}
