//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectE2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportCardTeacher
    {
        public int Id { get; set; }
        public int TeacherId { get; set; }
        public int ReportCardId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ReportCard ReportCard { get; set; }
    }
}
