//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationalPartApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subgroup
    {
        public int Id { get; set; }
        public int TeacherId { get; set; }
        public int AuditoriumId { get; set; }
        public int ScheduleId { get; set; }
    
        public virtual Auditorium Auditorium { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
